### PR TITLE
moves scoped properties to settings

### PR DESCRIPTION
**Pull request by pierrickrouxel**
Atom throws a depreciation message because `scoped-properties` should be renamed `settings`.

### CODE REVIEW

**Comment by ghempton** [comment]
thanks!

**Comment by kpfefferle** [comment]
@ghempton Is there anything preventing this from being merged that we can help you out with? I am eagerly awaiting this PR removing my only remaining Atom deprecation warning :wink:

**Comment by ghempton** [comment]
Merges :)

**Comment by pierrickrouxel** [comment]
Thank you, can you release please ?

**Pull request merged**
